<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="14" passed="13">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="26120" started-at="2019-07-04T18:57:21Z" finished-at="2019-07-04T18:57:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="26120" started-at="2019-07-04T18:57:21Z" finished-at="2019-07-04T18:57:47Z">
      <class name="Testcases.apptest">
        <test-method status="PASS" signature="Browsertest()[pri:0, instance:Testcases.apptest@5b275dab]" name="Browsertest" is-config="true" duration-ms="4283" started-at="2019-07-04T18:57:21Z" finished-at="2019-07-04T18:57:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Browsertest -->
        <test-method status="PASS" signature="verifyURl()[pri:0, instance:Testcases.apptest@5b275dab]" name="verifyURl" duration-ms="1584" started-at="2019-07-04T18:57:25Z" finished-at="2019-07-04T18:57:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyURl -->
        <test-method status="PASS" signature="verifytitle()[pri:1, instance:Testcases.apptest@5b275dab]" name="verifytitle" duration-ms="22" started-at="2019-07-04T18:57:27Z" finished-at="2019-07-04T18:57:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifytitle -->
        <test-method status="PASS" signature="verifyloginbuttonText()[pri:2, instance:Testcases.apptest@5b275dab]" name="verifyloginbuttonText" duration-ms="52" started-at="2019-07-04T18:57:27Z" finished-at="2019-07-04T18:57:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyloginbuttonText -->
        <test-method status="PASS" signature="verifyloginheadingText()[pri:3, instance:Testcases.apptest@5b275dab]" name="verifyloginheadingText" duration-ms="65" started-at="2019-07-04T18:57:27Z" finished-at="2019-07-04T18:57:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyloginheadingText -->
        <test-method status="PASS" signature="verifyforgotpasswordtext()[pri:4, instance:Testcases.apptest@5b275dab]" name="verifyforgotpasswordtext" duration-ms="1444" started-at="2019-07-04T18:57:27Z" finished-at="2019-07-04T18:57:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyforgotpasswordtext -->
        <test-method status="PASS" signature="verifyforgotpassheadingtext()[pri:5, instance:Testcases.apptest@5b275dab]" name="verifyforgotpassheadingtext" duration-ms="21" started-at="2019-07-04T18:57:29Z" finished-at="2019-07-04T18:57:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyforgotpassheadingtext -->
        <test-method status="PASS" signature="verifyforgotpassusernamelabel()[pri:6, instance:Testcases.apptest@5b275dab]" name="verifyforgotpassusernamelabel" duration-ms="57" started-at="2019-07-04T18:57:29Z" finished-at="2019-07-04T18:57:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyforgotpassusernamelabel -->
        <test-method status="PASS" signature="verifyresetpasswordbuttontext()[pri:7, instance:Testcases.apptest@5b275dab]" name="verifyresetpasswordbuttontext" duration-ms="2770" started-at="2019-07-04T18:57:29Z" finished-at="2019-07-04T18:57:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyresetpasswordbuttontext -->
        <test-method status="PASS" signature="verifyloginwithvalidusername()[pri:8, instance:Testcases.apptest@5b275dab]" name="verifyloginwithvalidusername" duration-ms="1793" started-at="2019-07-04T18:57:31Z" finished-at="2019-07-04T18:57:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyloginwithvalidusername -->
        <test-method status="PASS" signature="verifylogiwithvalidpassword()[pri:9, instance:Testcases.apptest@5b275dab]" name="verifylogiwithvalidpassword" duration-ms="1447" started-at="2019-07-04T18:57:33Z" finished-at="2019-07-04T18:57:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifylogiwithvalidpassword -->
        <test-method status="PASS" signature="verifyloginwithwrongusernameandpassword()[pri:10, instance:Testcases.apptest@5b275dab]" name="verifyloginwithwrongusernameandpassword" duration-ms="1483" started-at="2019-07-04T18:57:35Z" finished-at="2019-07-04T18:57:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyloginwithwrongusernameandpassword -->
        <test-method status="PASS" signature="verifyloginwithblank()[pri:11, instance:Testcases.apptest@5b275dab]" name="verifyloginwithblank" duration-ms="231" started-at="2019-07-04T18:57:36Z" finished-at="2019-07-04T18:57:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyloginwithblank -->
        <test-method status="PASS" signature="verifylogin()[pri:12, instance:Testcases.apptest@5b275dab]" name="verifylogin" duration-ms="3172" started-at="2019-07-04T18:57:36Z" finished-at="2019-07-04T18:57:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifylogin -->
        <test-method status="FAIL" signature="addadmin()[pri:13, instance:Testcases.apptest@5b275dab]" name="addadmin" duration-ms="7640" started-at="2019-07-04T18:57:40Z" finished-at="2019-07-04T18:57:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Already exist] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Already exist] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.techbeamers.base.BaseTest.adduser(BaseTest.java:140)
at Testcases.apptest.addadmin(apptest.java:98)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addadmin -->
      </class> <!-- Testcases.apptest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
